"""
JWT token handling and validation utilities.

This module provides functions for decoding and validating JWT tokens using
the configured algorithm (default HS256). It handles token expiration,
invalid signatures, and malformed tokens with appropriate error handling.

PUBLIC_INTERFACE
"""
from datetime import datetime, timedelta
from typing import Optional, Dict, Any
import logging

from jose import JWTError, jwt, ExpiredSignatureError
from jose.exceptions import JWTClaimsError

from src.config.settings import get_settings

# Module-level logger
logger = logging.getLogger(__name__)


class JWTValidationError(Exception):
    """
    Base exception for JWT validation errors.
    
    @compliance
    - Security: Specific error type for authentication failures
    """
    pass


class TokenExpiredError(JWTValidationError):
    """
    Exception raised when JWT token has expired.
    
    @compliance
    - Security: Clear error for expired tokens
    """
    pass


class InvalidTokenError(JWTValidationError):
    """
    Exception raised when JWT token is invalid or malformed.
    
    @compliance
    - Security: Clear error for invalid tokens
    """
    pass


# PUBLIC_INTERFACE
def create_access_token(data: Dict[str, Any], expires_delta: Optional[timedelta] = None) -> str:
    """
    Create a JWT access token with the provided data.
    
    This function is primarily used for testing and development. In production,
    tokens should be generated by the authentication service.
    
    Args:
        data: Dictionary of claims to include in the token
        expires_delta: Optional custom expiration time, defaults to settings value
        
    Returns:
        str: Encoded JWT token
        
    Example:
        >>> token = create_access_token({"user_id": "user123"})
        >>> print(token)
        eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        
    @compliance
    - Security: Uses configured secret and algorithm
    - Standards: JWT standard claims (exp, iat)
    
    Note:
        The JWT_SECRET_KEY environment variable must be set (min 32 characters)
    """
    settings = get_settings()
    
    to_encode = data.copy()
    
    # Set expiration time
    if expires_delta:
        expire = datetime.utcnow() + expires_delta
    else:
        expire = datetime.utcnow() + timedelta(minutes=settings.jwt_expiration_minutes)
    
    # Add standard claims
    to_encode.update({
        "exp": expire,
        "iat": datetime.utcnow()
    })
    
    # Encode token
    encoded_jwt = jwt.encode(
        to_encode,
        settings.jwt_secret_key,
        algorithm=settings.jwt_algorithm
    )
    
    logger.debug(
        "JWT token created",
        extra={
            "user_id": data.get("user_id", "unknown"),
            "expires_at": expire.isoformat()
        }
    )
    
    return encoded_jwt


# PUBLIC_INTERFACE
def decode_token(token: str) -> Dict[str, Any]:
    """
    Decode and validate a JWT token.
    
    This function validates the token signature, checks expiration,
    and returns the decoded payload if valid.
    
    Args:
        token: JWT token string to decode
        
    Returns:
        Dict[str, Any]: Decoded token payload containing claims
        
    Raises:
        TokenExpiredError: If token has expired
        InvalidTokenError: If token is malformed or signature is invalid
        
    Example:
        >>> token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        >>> payload = decode_token(token)
        >>> print(payload["user_id"])
        user123
        
    @compliance
    - Security: Validates signature using secret key
    - Security: Checks token expiration
    - Error Handling: Specific errors for different failure modes
    
    Note:
        The JWT_SECRET_KEY environment variable must match the key used to sign the token
    """
    if not token or not token.strip():
        raise InvalidTokenError("Token cannot be empty")
    
    settings = get_settings()
    
    try:
        # Decode and validate token
        payload = jwt.decode(
            token,
            settings.jwt_secret_key,
            algorithms=[settings.jwt_algorithm]
        )
        
        logger.debug(
            "JWT token decoded successfully",
            extra={
                "user_id": payload.get("user_id", "unknown"),
                "exp": payload.get("exp")
            }
        )
        
        return payload
        
    except ExpiredSignatureError as e:
        logger.warning(
            "JWT token expired",
            extra={"error": str(e)}
        )
        raise TokenExpiredError("Token has expired") from e
        
    except JWTClaimsError as e:
        logger.warning(
            "JWT claims validation failed",
            extra={"error": str(e)}
        )
        raise InvalidTokenError("Token claims are invalid") from e
        
    except JWTError as e:
        logger.warning(
            "JWT validation failed",
            extra={"error": str(e)}
        )
        raise InvalidTokenError("Invalid token") from e
        
    except Exception as e:
        logger.error(
            "Unexpected error decoding JWT",
            extra={"error": str(e)},
            exc_info=True
        )
        raise InvalidTokenError("Token validation failed") from e


# PUBLIC_INTERFACE
def validate_token(token: str) -> bool:
    """
    Validate a JWT token without returning the payload.
    
    This is a convenience function for checking if a token is valid
    without needing the payload data.
    
    Args:
        token: JWT token string to validate
        
    Returns:
        bool: True if token is valid, False otherwise
        
    Example:
        >>> token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        >>> if validate_token(token):
        ...     print("Token is valid")
        
    @compliance
    - Security: Performs full validation including signature and expiration
    """
    try:
        decode_token(token)
        return True
    except (TokenExpiredError, InvalidTokenError):
        return False


# PUBLIC_INTERFACE
def extract_user_id(token: str) -> str:
    """
    Extract user_id from a JWT token.
    
    This is a convenience function that decodes the token and extracts
    the user_id claim. Raises an error if user_id is not present.
    
    Args:
        token: JWT token string containing user_id claim
        
    Returns:
        str: User ID from token
        
    Raises:
        TokenExpiredError: If token has expired
        InvalidTokenError: If token is invalid or missing user_id
        
    Example:
        >>> token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        >>> user_id = extract_user_id(token)
        >>> print(user_id)
        user123
        
    @compliance
    - Security: Validates token before extracting user_id
    - Data Integrity: Ensures user_id exists in token
    """
    payload = decode_token(token)
    
    user_id = payload.get("user_id")
    if not user_id:
        raise InvalidTokenError("Token does not contain user_id claim")
    
    if not isinstance(user_id, str) or not user_id.strip():
        raise InvalidTokenError("user_id claim is invalid")
    
    return user_id.strip()


# PUBLIC_INTERFACE
def get_token_expiration(token: str) -> Optional[datetime]:
    """
    Get the expiration time from a JWT token.
    
    Args:
        token: JWT token string
        
    Returns:
        Optional[datetime]: Expiration datetime in UTC, or None if not present
        
    Raises:
        TokenExpiredError: If token has expired
        InvalidTokenError: If token is invalid
        
    Example:
        >>> token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        >>> exp_time = get_token_expiration(token)
        >>> print(exp_time)
        2025-01-12 11:30:00
        
    @compliance
    - Standards: JWT standard 'exp' claim
    """
    payload = decode_token(token)
    
    exp_timestamp = payload.get("exp")
    if exp_timestamp:
        return datetime.utcfromtimestamp(exp_timestamp)
    
    return None
